swagger: "2.0"
info: 
  version: "1.5"
  title: "Meetup API"
  description: "This api will be used to generate and query Meetups"
  termsOfService: "https://google.com"
  contact:
    email: "oga@oga.com"
  license:
    name: "Apache 2.0"
    url: "http://bing.com"
basePath: "/api"
tags: 
- name: "Meetups"
  description: "Method for managing meetups"
  externalDocs:
    description: "Centralized info"
    url: "http://swagger.com"
schemes:
- "https"
- "http"
paths: 
  /meetup:
    get:
      tags:
      - "Meetups"
      summary: "Get the list of active meetups"
      operationId: "getAllMeetups"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "date" 
        in: "query"
        type: "string"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Meetup"
    post:
      tags:
      - "Meetups"
      summary: "Adds a new meetup"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Meetup to be added"
        required: true
        schema:
          $ref: "#/definitions/Meetup"
      responses:
        405:
          description: "Invalid input"
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Meetup"
  /meetup/{id}:
    get:
      tags:
      - "Meetups"
      summary: "Get the specifed Meetup information"
      operationId: "getMeetup"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "id"
        in: "path"
        type: "string"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Meetup"
        404:
          description: "Not found"
    put:
      tags:
      - "Meetups"
      summary: "Update the specifed Meetup information"
      operationId: "setMeetup"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "id"
        in: "path"
        type: "string"
        required: true
      - name: "body"
        in: "body"
        description: "Meetup to be updated"
        required: true
        schema:
          $ref: "#/definitions/Meetup"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Meetup"
        404:
          description: "Not found"      
definitions:
  Meetup:
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: "5"
        description: "The meetup Id"
      name:
        type: "string"
        example: "My wonderfull meetup"
        description: "The name of the meetup"
      location:
        type: "string"
        example: "Palacio de los deportes"
        description: "The meetup geographical location"