version: '3.4'

services:
  hk-mysql:
    container_name: hk-mysql
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: Certum#01
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always
  courses:
    image: containersoga/courses
    build: .
    ports:
      - 8080:8080
    depends_on:
    - hk-mysql
